title: Bryan Ramos
description: Linux Systems & Automation Engineer
url: "https://ramos.codes"

include:
  - ".well-known"

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
