title: Bryan Ramos
description: Open source systems engineer working with Linux, Nix, automation, and local AI
url: "https://ramos.codes"

include:
  - ".well-known"

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

exclude:
  - flake.nix
  - flake.lock
  - justfile
